CREATE TABLE IF NOT EXISTS TB_CHART
(
    ID          INT NOT NULL AUTO_INCREMENT,
    CHART_NAME  VARCHAR2(30),
    VERSION     NUMBER,
    UPDATE_USER VARCHAR2(10),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TB_CURRENCY
(
    CODE        VARCHAR2(5),
    NAME_EN     VARCHAR2(50),
    NAME_TW     VARCHAR2(50),
    VERSION     NUMBER,
    UPDATE_USER VARCHAR2(10),
    UPD_DT      TIMESTAMP,
    PRIMARY KEY (CODE)
);

CREATE TABLE IF NOT EXISTS TB_CHART_RATE
(
    CHART_ID      INT,
    CURRENCY_CODE VARCHAR2(5),
    RATE          FLOAT,
    VERSION       NUMBER,
    UPDATE_USER   VARCHAR2(10),
    PRIMARY KEY (CHART_ID, CURRENCY_CODE)
);

CREATE TABLE IF NOT EXISTS TB_ACCOUNT_KEY
(
    ACCOUNT_ID VARCHAR2(100),
    API_KEY    VARCHAR2(50),
    PRIMARY KEY (ACCOUNT_ID)
);

INSERT INTO TB_CURRENCY (CODE, NAME_EN, NAME_TW, VERSION, UPDATE_USER, UPD_DT)
SELECT 'USD', 'United States Dollar', '美金', 1, 'default', CURRENT_TIMESTAMP()
FROM dual
WHERE NOT EXISTS(SELECT 1 FROM TB_CURRENCY WHERE CODE = 'USD');

INSERT INTO TB_CURRENCY (CODE, NAME_EN, NAME_TW, VERSION, UPDATE_USER, UPD_DT)
SELECT 'GBP', 'British Pound Sterling', '英鎊', 1, 'default', CURRENT_TIMESTAMP()
FROM dual
WHERE NOT EXISTS(SELECT 1 FROM TB_CURRENCY WHERE CODE = 'GBP');

INSERT INTO TB_CURRENCY (CODE, NAME_EN, NAME_TW, VERSION, UPDATE_USER, UPD_DT)
SELECT 'EUR', 'Euro', '歐元', 1, 'default', CURRENT_TIMESTAMP()
FROM dual
WHERE NOT EXISTS(SELECT 1 FROM TB_CURRENCY WHERE CODE = 'EUR');

INSERT INTO TB_ACCOUNT_KEY (ACCOUNT_ID, API_KEY)
SELECT 'demo', 'demo_for_test'
FROM dual
WHERE NOT EXISTS(SELECT 1 FROM TB_ACCOUNT_KEY WHERE ACCOUNT_ID = 'demo');